export const SELECT_TWITCH_CHANNEL = 'SELECT_TWITCH_CHANNEL';
export const ON_TWITCH_INPUT = 'ON_TWITCH_INPUT';
export const SET_TWITCH_CHANNELS = 'SET_TWITCH_CHANNELS';
export const SET_TWITCH_CHANNEL = 'SET_TWITCH_CHANNEL';
