export const SET_SIDEBAR_TOGGLE = 'SET_SIDEBAR_TOGGLE';
export const SET_CHANNELS = 'SET_CHANNELS';
export const SELECT_CHANNEL = 'SELECT_CHANNEL';
export const SELECT_VIDEO = 'SELECT_VIDEO';
export const SET_VIDEOS = 'SET_VIDEOS';
export const ADD_CHANNEL = 'ADD_CHANNEL';
export const ON_USERNAME_INPUT = 'ON_USERNAME_INPUT';