export const SET_SIDEBAR_TOGGLE = "SET_SIDEBAR_TOGGLE";
export const GET_USER_STATUS = "GET_USER_STATUS";
export const SET_NAVBAR_TOGGLE = "SET_NAVBAR_TOGGLE";
export const SIGNUP = "SIGNUP";
export const CHANGE_LOGIN_STATUS = "CHANGE_LOGIN_STATUS";
