export const SET_SUBREDDIT_POSTS = "SET_SUBREDDIT_POSTS";
export const SET_SUBREDDITS = "SET_SUBREDDITS";
export const ON_SUBREDDIT_INPUT = "ON_SUBREDDIT_INPUT";
export const SELECT_SUBREDDIT = "SELECT_SUBREDDIT";
